name: VoiceFlow
options:
  bundleIdPrefix: com.voiceflow
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  VoiceFlow:
    type: application
    platform: macOS
    sources:
      - path: Sources
        type: group
      - path: Resources
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.voiceflow.app
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Resources/VoiceFlow.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_IDENTITY: "-"
        PRODUCT_NAME: VoiceFlow
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
    entitlements:
      path: Resources/VoiceFlow.entitlements
